<?php

namespace Database\Seeders;

use App\Models\Community;
use App\Models\Flair;
use App\Models\Post;
use App\Models\User;
use Illuminate\Support\Facades\Schema;
use Illuminate\Support\Facades\DB;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class PostSeeder extends Seeder
{
    /**
     * Default global flairs to ensure availability for seeded posts.
     *
     * @return array<int, array<string,string|bool>>
     */
    private function defaultFlairs(): array
    {
        return [
            ['name' => 'Balik Sinta Stories', 'slug' => 'balik-sinta-stories', 'color' => '#F59E0B', 'icon' => '📖'],
            ['name' => 'Announcement', 'slug' => 'announcement', 'color' => '#6366F1', 'icon' => '📢'],
            ['name' => 'Event / Webinar', 'slug' => 'event-webinar', 'color' => '#10B981', 'icon' => '🗓️'],
            ['name' => 'Advice', 'slug' => 'advice', 'color' => '#EF4444', 'icon' => '💡'],
            ['name' => 'Job Referral', 'slug' => 'job-referral', 'color' => '#0EA5E9', 'icon' => '💼'],
            ['name' => 'Mentorship', 'slug' => 'mentorship', 'color' => '#8B5CF6', 'icon' => '🤝'],
            ['name' => 'Alumni Spotlight', 'slug' => 'alumni-spotlight', 'color' => '#F97316', 'icon' => '✨'],
            ['name' => 'Resources', 'slug' => 'resources', 'color' => '#06B6D4', 'icon' => '📚'],
            ['name' => 'Volunteer Opportunity', 'slug' => 'volunteer-opportunity', 'color' => '#84CC16', 'icon' => '🙋‍♂️'],
            ['name' => 'Research & Publications', 'slug' => 'research-publications', 'color' => '#0EA5E9', 'icon' => '🔬'],
            ['name' => 'Career Tips', 'slug' => 'career-tips', 'color' => '#FB7185', 'icon' => '🎯'],
            ['name' => 'Question', 'slug' => 'question', 'color' => '#F97316', 'icon' => '❓'],
            ['name' => 'Showcase', 'slug' => 'showcase', 'color' => '#06B6D4', 'icon' => '🏆'],
            ['name' => 'School News', 'slug' => 'school-news', 'color' => '#334155', 'icon' => '🏫'],
        ];
    }

    public function run(): void
    {
        // Ensure global flairs exist
        foreach ($this->defaultFlairs() as $f) {
            // Some environments may have an older flairs table without `slug` column.
            if (Schema::hasTable('flairs') && Schema::hasColumn('flairs', 'slug')) {
                Flair::firstOrCreate(
                    ['slug' => $f['slug']],
                    ['name' => $f['name'], 'color' => $f['color'], 'icon' => $f['icon'], 'is_sticky' => false]
                );
            } else {
                Flair::firstOrCreate(
                    ['name' => $f['name']],
                    ['color' => $f['color'], 'icon' => $f['icon'], 'is_sticky' => false]
                );
            }
        }

        $flairIds = Flair::global()->pluck('id')->toArray();

        $communities = Community::all();
        if ($communities->isEmpty()) {
            $this->command->info('No communities found, skipping post seeding.');
            return;
        }

        // Clear existing posts to ensure fresh seeding with new markdown conversion
        // Truncate pivot table first, then posts (due to foreign key constraints)
        DB::table('flair_post')->truncate();
        Post::query()->delete();  // Use delete instead of truncate due to FK constraints

        foreach ($communities as $community) {
            // pick a pool of eligible users: community members or any user as fallback
            $memberIds = [];
            try {
                $memberIds = $community->members()->pluck('user_id')->toArray();
            } catch (\Throwable $e) {
                // ignore if relation not present
            }

            if (empty($memberIds)) {
                $memberIds = User::query()->pluck('id')->toArray();
            }

            if (empty($memberIds)) {
                $this->command->info('No users available to assign posts for community: ' . $community->id);
                continue;
            }

            // create 12 posts per community
            for ($i = 1; $i <= 12; $i++) {
                $title = sprintf('%s — Sample Post %02d', $community->name, $i);
                $body = "**Sample content** for {$community->name}. This is seeded post number {$i}.\n\n";
                $body .= "- This post demonstrates flairs, markdown rendering, and attachments placeholder.\n";
                $body .= "\n_This is autogenerated seed data._";

                $userId = $memberIds[array_rand($memberIds)];

                $post = Post::create([
                    'community_id' => $community->id,
                    'user_id' => $userId,
                    'title' => $title,
                    'body_markdown' => $body,
                    'status' => 'published',
                    'visibility' => 'members',
                    'pinned' => false,
                    'comment_count' => rand(0, 12),
                    'view_count' => rand(1, 500),
                    'like_count' => rand(0, 50),
                    'published_at' => now()->subDays(rand(0, 30)),
                ]);

                // attach 1-2 random flairs (community-specific or global)
                $possible = Flair::forCommunity($community->id)->inRandomOrder()->limit(rand(1, 2))->pluck('id')->toArray();
                if (!empty($possible)) {
                    $post->flairs()->sync($possible);
                }
            }
        }

        $this->command->info('Seeded posts for ' . $communities->count() . ' communities.');
    }
}
