<?php

namespace App\Http\Controllers;

use App\Http\Requests\ProfileUpdateRequest;
use App\Models\Connection;
use App\Models\Post;
use App\Models\User;
use App\Services\ImageOptimizer;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\Http\UploadedFile;
use Illuminate\Http\JsonResponse;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Redirect;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Str;
use Illuminate\View\View;

class ProfileController extends Controller
{
    public function __construct(private readonly ImageOptimizer $imageOptimizer) {}

    /**
     * Resize + compress an uploaded image, then store it. Falls back to storing
     * the original for formats the optimizer skips (e.g. GIF).
     */
    private function storeOptimizedImage(UploadedFile $file, string $directory, int $maxDimension): string
    {
        $optimized = $this->imageOptimizer->optimize($file, $maxDimension);

        if ($optimized) {
            $path = $directory . '/' . Str::random(40) . '.' . $optimized['extension'];
            Storage::put($path, $optimized['contents'], ['CacheControl' => ImageOptimizer::CACHE_CONTROL]);

            return $path;
        }

        return $file->store($directory, ['CacheControl' => ImageOptimizer::CACHE_CONTROL]);
    }

    public function show(Request $request, User $user): View
    {
        // Admin accounts are staff, not alumni — they have no public profile
        // (no career profile, activity, etc.), so block direct access to them.
        // Superadmin/institution profiles remain public (official account).
        abort_if($user->role === 'admin', 404);

        $viewer = $request->user();
        $user->load(['profileExperiences', 'profileEducations']);

        $connectionState = null;
        $activeConnection = null;

        if (! $viewer->is($user)) {
            [$lowId, $highId] = Connection::normalizedPair($viewer->id, $user->id);

            $activeConnection = Connection::query()
                ->where('user_low_id', $lowId)
                ->where('user_high_id', $highId)
                ->first();

            if ($activeConnection) {
                $connectionState = match ($activeConnection->status) {
                    Connection::STATUS_ACCEPTED => 'connected',
                    Connection::STATUS_PENDING => $activeConnection->sender_id === $viewer->id
                        ? 'invite_sent'
                        : 'invite_received',
                    default => null,
                };
            }
        }

        $activityPostsQuery = Post::query()
            ->with(['user', 'community', 'flairs', 'media'])
            ->withCount(['allComments as comments_count', 'likes'])
            ->where('status', 'published')
            ->whereNull('trashed_at')
            ->where('user_id', $user->id)
            ->where(function ($q) {
                $q->whereNull('body_markdown')
                    ->orWhere('body_markdown', 'not like', '%autogenerated seed data%');
            })
            ->where(function ($q) {
                $q->whereNull('title')
                    ->orWhere('title', 'not like', '%Sample Post%');
            })
            ->orderByDesc('published_at')
            ->orderByDesc('id');

        if (! $viewer->is($user)) {
            $memberCommunityIds = $viewer->communities()->pluck('communities.id');
            $isConnected = $viewer->isConnectedWith($user);

            $activityPostsQuery->where(function ($q) use ($memberCommunityIds, $isConnected) {
                $q->where('visibility', 'public')
                    ->orWhere(function ($q2) use ($memberCommunityIds) {
                        $q2->where('visibility', 'members')
                            ->whereIn('community_id', $memberCommunityIds);
                    });

                if ($isConnected) {
                    $q->orWhere('visibility', 'connections');
                }
            });
        }

        $activityPosts = $activityPostsQuery->get();

        $connectionCount = $user->connections()->count();

        // Composer config for editing own posts from the profile (same audience
        // logic as the dashboard: General Hub → Everyone; program/batch →
        // public/connections/community). Only needed on the viewer's own profile.
        $joinedCommunities = collect();
        $flairsByCommunity = collect();
        if ($viewer->is($user)) {
            $joinedCommunities = $viewer->communities()
                ->orderBy('name')
                ->get(['communities.id', 'communities.name', 'communities.system_key']);

            $availableFlairs = \App\Models\Flair::query()
                ->whereNull('community_id')
                ->orWhereIn('community_id', $joinedCommunities->pluck('id'))
                ->get();

            $flairsByCommunity = $availableFlairs
                ->where('is_system', false)
                ->groupBy(fn ($f) => $f->community_id ?? 'global')
                ->map(fn ($group) => $group->values()->map(fn ($f) => [
                    'id' => $f->id, 'name' => $f->name, 'color' => $f->color, 'icon' => $f->icon,
                ]));
        }

        return view('profile.show', [
            'profileUser' => $user,
            'viewer' => $viewer,
            'showFullDetails' => $viewer->is($user) || ! $viewer->hasLimitedProfileVisibility(),
            'connectionState' => $connectionState,
            'activeConnection' => $activeConnection,
            'activityPosts' => $activityPosts,
            'connectionCount' => $connectionCount,
            'joinedCommunities' => $joinedCommunities,
            'flairsByCommunity' => $flairsByCommunity,
        ]);
    }

    /**
     * Display the user's profile form.
     */
    public function edit(Request $request): View
    {
        // The institution account has no editable profile/career information.
        abort_if($request->user()->isInstitution(), 403);

        $request->user()->load(['profileExperiences', 'profileEducations']);

        return view('profile.edit', [
            'user' => $request->user(),
        ]);
    }

    /**
     * Update the user's profile information.
     */
    public function update(ProfileUpdateRequest $request): RedirectResponse
    {
        $validated = $request->validated();
        $user = $request->user();

        // The institution account can update only its avatar/banner (branding) —
        // never the name/program/career profile information.
        if ($user->isInstitution()) {
            if ($request->hasFile('avatar')) {
                $oldAvatarPath = $user->avatar_path;
                $user->avatar_path = $this->storeOptimizedImage($request->file('avatar'), 'avatars/user_' . $user->id, 512);
                $user->avatar_uploaded_at = now();
                if ($oldAvatarPath && Storage::exists($oldAvatarPath)) {
                    Storage::delete($oldAvatarPath);
                }
            }

            if ($request->hasFile('banner')) {
                $oldBannerPath = $user->banner_path;
                $user->banner_path = $this->storeOptimizedImage($request->file('banner'), 'banners/user_' . $user->id, 1600);
                $user->banner_uploaded_at = now();
                if ($oldBannerPath && Storage::exists($oldBannerPath)) {
                    Storage::delete($oldBannerPath);
                }
            }

            $user->save();

            return $request->input('redirect_to') === 'profile_show'
                ? Redirect::route('profiles.show', $user)->with('status', 'profile-updated')
                : Redirect::to('/profile')->with('status', 'profile-updated');
        }

        $firstName = Str::of($validated['first_name'])->trim()->value();
        $lastName = Str::of($validated['last_name'])->trim()->value();
        $skills = collect(explode(',', (string) ($validated['skills'] ?? '')))
            ->map(fn(string $skill) => trim($skill))
            ->filter(fn(string $skill) => $skill !== '')
            ->unique()
            ->values();

        $user->fill([
            'name' => trim($firstName . ' ' . $lastName),
            'first_name' => $firstName,
            'last_name' => $lastName,
            'email' => Str::of($validated['email'])->trim()->value(),
            'skills' => $skills->isEmpty() ? null : $skills->implode(', '),
        ]);

        if ($request->hasFile('avatar')) {
            $oldAvatarPath = $user->avatar_path;
            $newAvatarPath = $this->storeOptimizedImage($request->file('avatar'), 'avatars/user_' . $user->id, 512);

            $user->avatar_path = $newAvatarPath;
            $user->avatar_uploaded_at = now();

            if ($oldAvatarPath && Storage::exists($oldAvatarPath)) {
                Storage::delete($oldAvatarPath);
            }
        }

        if ($request->hasFile('banner')) {
            $oldBannerPath = $user->banner_path;
            $newBannerPath = $this->storeOptimizedImage($request->file('banner'), 'banners/user_' . $user->id, 1600);

            $user->banner_path = $newBannerPath;
            $user->banner_uploaded_at = now();

            if ($oldBannerPath && Storage::exists($oldBannerPath)) {
                Storage::delete($oldBannerPath);
            }
        }

        if ($user->isDirty('email')) {
            $user->email_verified_at = null;
        }

        DB::transaction(function () use ($user, $validated): void {
            $user->save();

            $submittedExperiences = collect($validated['experiences'] ?? [])
                ->map(function (array $experience): array {
                    return [
                        'id' => isset($experience['id']) ? (int) $experience['id'] : null,
                        'title' => Str::of((string) ($experience['title'] ?? ''))->trim()->value(),
                        'organization' => Str::of((string) ($experience['organization'] ?? ''))->trim()->value(),
                        'start_date' => $this->normalizeExperienceMonth($experience['start_month'] ?? null),
                        'end_date' => $this->normalizeExperienceMonth($experience['end_month'] ?? null),
                        'description' => Str::of((string) ($experience['description'] ?? ''))->trim()->value(),
                    ];
                })
                ->filter(function (array $experience): bool {
                    return $experience['title'] !== ''
                        || $experience['organization'] !== ''
                        || $experience['start_date'] !== null
                        || $experience['end_date'] !== null
                        || $experience['description'] !== '';
                })
                ->values();

            $userExperienceIds = $user->profileExperiences()->pluck('id')->all();
            $keptExperienceIds = [];

            foreach ($submittedExperiences as $experience) {
                if ($experience['title'] === '' || $experience['organization'] === '') {
                    continue;
                }

                $payload = [
                    'title' => $experience['title'],
                    'organization' => $experience['organization'],
                    'start_date' => $experience['start_date'],
                    'end_date' => $experience['end_date'],
                    'description' => $experience['description'] === '' ? null : $experience['description'],
                ];

                if ($experience['id'] !== null && in_array($experience['id'], $userExperienceIds, true)) {
                    $user->profileExperiences()->whereKey($experience['id'])->update($payload);
                    $keptExperienceIds[] = $experience['id'];
                    continue;
                }

                $createdExperience = $user->profileExperiences()->create($payload);
                $keptExperienceIds[] = $createdExperience->id;
            }

            if (empty($keptExperienceIds)) {
                $user->profileExperiences()->delete();
            } else {
                $user->profileExperiences()->whereNotIn('id', $keptExperienceIds)->delete();
            }

            $submittedEducations = collect($validated['educations'] ?? [])
                ->map(function (array $education): array {
                    return [
                        'id' => isset($education['id']) ? (int) $education['id'] : null,
                        'school' => Str::of((string) ($education['school'] ?? ''))->trim()->value(),
                        'degree' => Str::of((string) ($education['degree'] ?? ''))->trim()->value(),
                        'start_date' => $this->normalizeDate($education['start_date'] ?? null),
                        'end_date' => $this->normalizeDate($education['end_date'] ?? null),
                    ];
                })
                ->filter(function (array $education): bool {
                    return $education['school'] !== ''
                        || $education['degree'] !== ''
                        || $education['start_date'] !== null
                        || $education['end_date'] !== null;
                })
                ->values();

            $userEducationIds = $user->profileEducations()->pluck('id')->all();
            $keptEducationIds = [];

            foreach ($submittedEducations as $education) {
                if ($education['school'] === '' || $education['degree'] === '') {
                    continue;
                }

                $payload = [
                    'school' => $education['school'],
                    'degree' => $education['degree'],
                    'start_date' => $education['start_date'],
                    'end_date' => $education['end_date'],
                ];

                if ($education['id'] !== null && in_array($education['id'], $userEducationIds, true)) {
                    $user->profileEducations()->whereKey($education['id'])->update($payload);
                    $keptEducationIds[] = $education['id'];
                    continue;
                }

                $createdEducation = $user->profileEducations()->create($payload);
                $keptEducationIds[] = $createdEducation->id;
            }

            if (empty($keptEducationIds)) {
                $user->profileEducations()->delete();
            } else {
                $user->profileEducations()->whereNotIn('id', $keptEducationIds)->delete();
            }
        });

        if ($request->input('redirect_to') === 'profile_show') {
            return Redirect::route('profiles.show', $user)->with('status', 'profile-updated');
        }

        return Redirect::route('profile.edit', ['section' => 'profile-information'])
            ->with('status', 'profile-updated');
    }

    private function normalizeExperienceMonth(?string $month): ?string
    {
        if (! $month) {
            return null;
        }

        $monthValue = trim($month);

        if ($monthValue === '') {
            return null;
        }

        return $monthValue . '-01';
    }

    private function normalizeDate(?string $date): ?string
    {
        if (! $date) {
            return null;
        }

        $dateValue = trim($date);

        if ($dateValue === '') {
            return null;
        }

        return $dateValue;
    }

    public function onboardingStep(Request $request): JsonResponse
    {
        abort_if($request->user()->isInstitution(), 403);

        $user = $request->user();
        $step = (int) $request->input('step', 0);

        if ($step === 1) {
            $request->validate(['avatar' => ['nullable', 'image', 'mimes:jpg,jpeg,png,webp', 'max:20480']]);
            if ($request->hasFile('avatar')) {
                $oldPath = $user->avatar_path;
                $user->avatar_path = $this->storeOptimizedImage($request->file('avatar'), 'avatars/user_' . $user->id, 512);
                $user->avatar_uploaded_at = now();
                $user->save();
                if ($oldPath && Storage::exists($oldPath)) {
                    Storage::delete($oldPath);
                }
            }
        } elseif ($step === 2) {
            $request->validate(['banner' => ['nullable', 'image', 'mimes:jpg,jpeg,png,webp', 'max:20480']]);
            if ($request->hasFile('banner')) {
                $oldPath = $user->banner_path;
                $user->banner_path = $this->storeOptimizedImage($request->file('banner'), 'banners/user_' . $user->id, 1600);
                $user->banner_uploaded_at = now();
                $user->save();
                if ($oldPath && Storage::exists($oldPath)) {
                    Storage::delete($oldPath);
                }
            }
        } elseif ($step === 3) {
            $request->validate([
                'experiences'               => ['nullable', 'array', 'max:10'],
                'experiences.*.title'       => ['nullable', 'string', 'max:120'],
                'experiences.*.organization'=> ['nullable', 'string', 'max:120'],
                'experiences.*.start_month' => ['nullable', 'date_format:Y-m', 'before_or_equal:' . now()->format('Y-m')],
                'experiences.*.end_month'   => ['nullable', 'date_format:Y-m', 'after_or_equal:experiences.*.start_month', 'before_or_equal:' . now()->format('Y-m')],
                'experiences.*.description' => ['nullable', 'string', 'max:1000'],
            ]);
            $entries = collect($request->input('experiences', []))
                ->map(fn($e) => [
                    'title'        => trim($e['title'] ?? ''),
                    'organization' => trim($e['organization'] ?? ''),
                    'start_date'   => ($e['start_month'] ?? '') ? $e['start_month'] . '-01' : null,
                    'end_date'     => ($e['end_month'] ?? '') ? $e['end_month'] . '-01' : null,
                    'description'  => trim($e['description'] ?? '') ?: null,
                ])
                ->filter(fn($e) => $e['title'] !== '' && $e['organization'] !== '' && $e['start_date'] !== null)
                ->values();
            if ($entries->isNotEmpty()) {
                DB::transaction(function () use ($user, $entries): void {
                    foreach ($entries as $entry) {
                        $user->profileExperiences()->create($entry);
                    }
                });
            }
        } elseif ($step === 4) {
            $request->validate([
                'educations'          => ['nullable', 'array', 'max:10'],
                'educations.*.school' => ['nullable', 'string', 'max:160'],
                'educations.*.degree' => ['nullable', 'string', 'max:160'],
                'educations.*.start_date' => ['nullable', 'date', 'before_or_equal:today'],
                'educations.*.end_date'   => ['nullable', 'date', 'after_or_equal:educations.*.start_date'],
            ]);
            $entries = collect($request->input('educations', []))
                ->map(fn($e) => [
                    'school'     => trim($e['school'] ?? ''),
                    'degree'     => trim($e['degree'] ?? ''),
                    'start_date' => ($e['start_date'] ?? '') ?: null,
                    'end_date'   => ($e['end_date'] ?? '') ?: null,
                ])
                ->filter(fn($e) => $e['school'] !== '' && $e['degree'] !== '' && $e['start_date'] !== null)
                ->values();
            if ($entries->isNotEmpty()) {
                DB::transaction(function () use ($user, $entries): void {
                    foreach ($entries as $entry) {
                        $user->profileEducations()->create($entry);
                    }
                });
            }
        } elseif ($step === 5) {
            $request->validate(['skills' => ['nullable', 'string', 'max:2000']]);
            $skills = collect(explode(',', (string) $request->input('skills', '')))
                ->map(fn($s) => trim($s))
                ->filter()
                ->unique()
                ->values();
            $user->skills = $skills->isEmpty() ? null : $skills->implode(', ');
            $user->save();
        }

        return response()->json(['ok' => true]);
    }

    /**
     * Mark the profile-setup wizard as completed so it stops appearing on future logins.
     */
    public function onboardingComplete(Request $request): JsonResponse
    {
        $request->user()->forceFill(['profile_setup_completed_at' => now()])->save();

        return response()->json(['ok' => true]);
    }

    /**
     * Delete the user's account.
     */
    public function destroy(Request $request): RedirectResponse
    {
        $request->validateWithBag('userDeletion', [
            'password' => ['required', 'current_password'],
        ]);

        $user = $request->user();

        if ($user->avatar_path && Storage::exists($user->avatar_path)) {
            Storage::delete($user->avatar_path);
        }

        if ($user->banner_path && Storage::exists($user->banner_path)) {
            Storage::delete($user->banner_path);
        }

        Auth::logout();

        $user->delete();

        $request->session()->invalidate();
        $request->session()->regenerateToken();

        return Redirect::to('/');
    }
}
